import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import crypto from 'node:crypto';
const require = createRequire(import.meta.url);
const E = require('../simulador/motor.js');
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
let passed = 0;
function test(name, fn) { fn(); passed++; console.log('OK ' + name); }
function atMain(options = {}) { let s = E.create(options); s = E.allPass(s).state; if (s.step === 'draw') s = E.allPass(s).state; assert.equal(s.step, 'main1'); return s; }
function cast(s, action, target) { const r = E.apply(s, action, s.priority, target); assert.equal(r.ok, true, r.message); return r.state; }
function until(s, step) { for (let i = 0; i < 35 && s.step !== step; i++) s = E.allPass(s).state; assert.equal(s.step, step); return s; }

test('conjurar retém prioridade e não resolve imediatamente', () => { const s = cast(atMain(), 'sorcery'); assert.equal(s.priority, 0); assert.equal(s.stack.length, 1); assert.equal(s.passes, 0); });
test('jogador sem prioridade é recusado sem modificar o estado', () => { const s = atMain(); const before = JSON.stringify(s); const r = E.apply(s, 'instant', 1); assert.equal(r.ok, false); assert.equal(r.state, s); assert.equal(JSON.stringify(s), before); });
test('criatura comum é recusada na manutenção e flash é permitido', () => { const s = E.create(); assert.equal(E.apply(s, 'creature', 0).ok, false); assert.equal(E.apply(s, 'flash', 0).ok, true); });
test('feitiçaria de jogador não ativo é recusada mesmo com prioridade', () => { const s = E.pass(atMain()).state; assert.equal(s.priority, 1); assert.equal(E.apply(s, 'sorcery', 1).ok, false); assert.equal(E.apply(s, 'instant', 1).ok, true); });
test('pilha cheia impede timing de feitiçaria', () => { const s = cast(atMain(), 'ability'); assert.equal(E.apply(s, 'creature', 0).ok, false); assert.equal(E.apply(s, 'loyalty', 0).ok, false); assert.equal(E.apply(s, 'flash', 0).ok, true); });
test('passe parcial não resolve objeto', () => { const s = E.pass(cast(atMain(), 'instant')).state; assert.equal(s.stack.length, 1); assert.equal(s.passes, 1); assert.equal(s.priority, 1); });
test('resposta interrompe passes e retém prioridade do respondente', () => { let s = E.pass(cast(atMain(), 'sorcery')).state; s = cast(s, 'instant'); assert.equal(s.passes, 0); assert.equal(s.priority, 1); assert.equal(s.stack.length, 2); });
test('todos passam resolve só o topo e prioridade retorna ao ativo', () => { let s = E.pass(cast(atMain(), 'sorcery')).state; s = cast(s, 'instant'); s = E.allPass(s).state; assert.equal(s.stack.length, 1); assert.equal(s.stack[0].action, 'sorcery'); assert.equal(s.priority, 0); assert.equal(s.step, 'main1'); });
test('todos passam completa apenas a rodada restante', () => { let s = cast(atMain(), 'instant'); s = E.pass(s).state; s = E.pass(s).state; s = E.allPass(s).state; assert.equal(s.stack.length, 0); assert.equal(s.step, 'main1'); assert.equal(s.passes, 0); });
test('pilha vazia e passes avançam só a fase seguinte', () => { const s = E.allPass(atMain()).state; assert.equal(s.step, 'beginCombat'); assert.equal(s.turn, 1); });
test('anular anulação preserva a mágica original', () => { let s = cast(atMain(), 'sorcery'); const original = s.stack[0].id; s = E.pass(s).state; s = cast(s, 'counter', original); const counter = s.stack.at(-1).id; s = E.pass(s).state; s = cast(s, 'counter', counter); s = E.allPass(s).state; assert.equal(s.stack.length, 1); assert.equal(s.stack[0].id, original); });
test('anulação mira somente mágica e aceita alvo abaixo do topo', () => { let s = cast(atMain(), 'sorcery'); const spell = s.stack[0].id; s = cast(s, 'ability'); assert.equal(E.apply(s, 'counter', 0, s.stack.at(-1).id).ok, false); assert.equal(E.apply(s, 'counter', 0, spell).ok, true); });
test('anulação com único alvo que saiu não resolve seu efeito', () => { let s = cast(atMain(), 'sorcery'); const target = s.stack[0].id; s = cast(s, 'counter', target); s = cast(s, 'counter', target); s = E.allPass(s).state; assert.equal(s.stack.length, 1); s = E.allPass(s).state; assert.equal(s.stack.length, 0); assert(s.log.some(l => l.text.includes('único alvo'))); });
test('terreno não usa pilha e só é jogado uma vez', () => { let s = cast(atMain(), 'land'); assert.equal(s.stack.length, 0); assert.equal(s.priority, 0); assert.equal(E.apply(s, 'land', 0).ok, false); s = until(s, 'main2'); assert.equal(E.apply(s, 'land', 0).ok, false); });
test('terreno pode ser guardado para a principal 2', () => { let s = until(atMain(), 'main2'); assert.equal(E.apply(s, 'land', 0).ok, true); });
test('mana válida não usa pilha e interrompe sequência de passes', () => { let s = E.pass(atMain()).state; s = cast(s, 'mana'); assert.equal(s.stack.length, 0); assert.equal(s.priority, 1); assert.equal(s.passes, 0); });
test('lealdade não renova na segunda principal', () => { let s = cast(atMain(), 'loyalty'); s = E.allPass(s).state; s = until(s, 'main2'); assert.equal(E.apply(s, 'loyalty', 0).ok, false); });
test('ETB aguarda em pilha separada e impede lealdade', () => { let s = cast(atMain(), 'creatureTrigger'); s = E.allPass(s).state; assert.equal(s.stack.length, 1); assert.equal(s.stack[0].kind, 'ability'); assert.equal(s.priority, 0); assert.equal(E.apply(s, 'loyalty', 0).ok, false); });
test('sem atacantes pula bloqueadores e dano', () => { let s = until(atMain({ hasAttackers: false }), 'attackers'); s = E.allPass(s).state; assert.equal(s.step, 'combatEnd'); });
test('combate normal oferece janela de bloqueadores antes do dano', () => { let s = until(atMain(), 'blockers'); assert(s.log.some(l => l.text.includes('Agora há janela antes do dano'))); s = E.allPass(s).state; assert.equal(s.step, 'damage'); assert(s.log.some(l => l.text.includes('já ocorreram SEM pilha'))); });
test('duas etapas de dano têm prioridades separadas', () => { let s = until(atMain({ firstStrike: true }), 'firstDamage'); assert.equal(s.priority, s.active); s = E.allPass(s).state; assert.equal(s.step, 'damage'); assert.equal(s.priority, s.active); });
test('limpeza normal não oferece prioridade', () => { let s = until(atMain(), 'end'); s = E.allPass(s).state; assert.equal(s.step, 'upkeep'); assert.equal(s.active, 1); assert.equal(s.turn, 2); assert(s.log.some(l => l.text.includes('Não há prioridade'))); });
test('gatilho na limpeza abre exceção e leva a nova limpeza', () => { let s = until(atMain({ cleanupTrigger: true }), 'end'); s = E.allPass(s).state; assert.equal(s.step, 'cleanup'); assert.equal(s.stack.length, 1); s = E.allPass(s).state; assert.equal(s.step, 'cleanup'); assert.equal(s.stack.length, 0); s = E.allPass(s).state; assert.equal(s.step, 'upkeep'); assert.equal(s.active, 1); assert.equal(s.log.filter(l => l.text.startsWith('Limpeza:')).length, 2); });
test('responder durante limpeza não pula a limpeza seguinte', () => { let s = until(atMain({ cleanupTrigger: true }), 'end'); s = E.allPass(s).state; s = cast(s, 'instant'); s = E.allPass(s).state; assert.equal(s.step, 'cleanup'); assert.equal(s.stack.length, 1); s = E.allPass(s).state; s = E.allPass(s).state; assert.equal(s.step, 'upkeep'); });
test('partida inicial multiplayer compra no primeiro turno', () => { const s = E.allPass(E.create({ count: 4 })).state; assert.equal(s.step, 'draw'); assert(s.log.some(l => l.text.includes('compra a carta normal'))); });
test('partida inicial de dois pula só a primeira compra do primeiro jogador', () => { let s = E.allPass(E.create({ count: 2 })).state; assert.equal(s.step, 'main1'); s = until(s, 'end'); s = E.allPass(s).state; assert.equal(s.active, 1); s = E.allPass(s).state; assert.equal(s.step, 'draw'); s = until(s, 'end'); s = E.allPass(s).state; assert.equal(s.active, 0); s = E.allPass(s).state; assert.equal(s.step, 'draw'); });
test('novo turno reinicia uso de terreno e lealdade', () => { let s = cast(atMain(), 'land'); s = cast(s, 'loyalty'); s = E.allPass(s).state; s = until(s, 'end'); s = E.allPass(s).state; assert(s.landPlayed.every(n => n === 0)); assert(s.loyaltyUsed.every(n => !n)); });
test('ordem de prioridade circula com seis jogadores', () => { let s = atMain({ count: 6 }); for (let p = 1; p < 6; p++) { s = E.pass(s).state; assert.equal(s.priority, p); } s = E.pass(s).state; assert.equal(s.step, 'beginCombat'); assert.equal(s.priority, 0); });
test('verificações e ações não alteram o objeto de estado anterior', () => { const s = atMain(); const snapshot = JSON.stringify(s); E.apply(s, 'land', 0); E.pass(s); E.allPass(s); assert.equal(JSON.stringify(s), snapshot); });

const readJSON = file => JSON.parse(fs.readFileSync(path.join(root, 'dados', file), 'utf8'));
const rules = readJSON('regras-completas.json'), glossary = readJSON('glossario-oficial.json');
const manifest = readJSON('manifesto.json'), scenarios = readJSON('cenarios.json');
test('manual local tem a cobertura declarada e hash correto', () => { const bytes = fs.readFileSync(path.join(root, 'fontes-oficiais/MagicCompRules-2026-09-25.txt')); assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'), manifest.local_sha256); assert.equal(bytes.toString('utf8').split('\n').length - 1, manifest.source_line_count); assert.equal(manifest.source_line_count, 8017); assert.deepEqual(manifest.source_line_gaps, []); });
test('índices contêm regras atuais e o fim do manual', () => { const byId = new Map(rules.map(r => [r.id, r])); for (const id of ['107.4', '117.4', '514.3a', '605.1a', '701.6', '702.124', '800.4j', '903.3', '903.9a', '905.6']) assert(byId.has(id), id); assert(byId.get('605.1a').text.includes('library')); assert(byId.get('903.3').text.includes('Spacecraft')); assert(glossary.some(g => g.term === 'First Strike')); assert.equal(rules.length, manifest.indexed_rule_entries); assert.equal(glossary.length, manifest.glossary_entries); });
test('cada cenário tem resposta válida e referências existentes', () => { const ids = new Set(rules.map(r => r.id)); assert.equal(new Set(scenarios.map(s => s.id)).size, scenarios.length); for (const s of scenarios) { assert(s.answer >= 0 && s.answer < s.options.length); assert(s.explanation.length > 20); for (const ref of s.rules) assert(ids.has(ref), ref); } assert.equal(scenarios.length, manifest.practice_scenarios); });
test('banidas distinguem Lutri companion e cartas desbanidas', () => { const b = readJSON('banidas-commander.json'); assert(b.banned_by_name.includes('Mana Crypt')); assert(!b.banned_by_name.includes('Biorhythm')); assert(!b.banned_by_name.includes('Lutri, the Spellchaser')); assert.deepEqual(b.banned_as_companion_only, ['Lutri, the Spellchaser']); });
test('todos os assuntos apontam a regras existentes', () => { const ids = new Set(rules.map(r => r.id)); for (const t of readJSON('indice-assuntos.json')) for (const ref of t.refs) assert(ids.has(ref), t.label + ': ' + ref); });
test('links e recursos locais das páginas entregues existem', () => { for (const file of ['ABRA-AQUI.html', 'simulador/index.html', 'guia/GUIA-PARA-IMPRIMIR.html']) { const absolute = path.join(root, file), markup = fs.readFileSync(absolute, 'utf8'); for (const m of markup.matchAll(/(?:href|src)="([^"]+)"/g)) { const target = m[1]; if (/^(?:https?:|#|data:)/.test(target)) continue; assert(fs.existsSync(path.resolve(path.dirname(absolute), target.split('#')[0])), file + ': ' + target); } assert(markup.includes('charset="utf-8"')); } });
test('dados da página offline carregam sem fetch ou CDN', () => { const dataSource = fs.readFileSync(path.join(root, 'simulador/dados.js'), 'utf8'); const payload = JSON.parse(dataSource.slice('window.MTG_DATA = '.length).trim().replace(/;$/, '').replace(/<\\\//g, '</')); assert.equal(payload.rules.length, rules.length); assert.equal(payload.scenarios.length, scenarios.length); const app = fs.readFileSync(path.join(root, 'simulador/app.js'), 'utf8'); assert(!/\bfetch\s*\(/.test(app)); });
console.log('\n' + passed + ' verificações passaram.');
